/** Auto-generated by npm run sync:videos — do not edit by hand.
 * Drop {agentId}.mp4 (or .webm/.mov) into public/agents/videos/ then run sync (or npm run dev/build).
 */
export const agentVideos: Record<string, string> = {
  "jay": "/agents/videos/jay.mp4",
};

export function getAgentVideo(id: string): string | undefined {
  return agentVideos[id];
}
