/** Filler Integration Center catalog — replace with real connectors later. */
export type IntegrationCard = {
  id: string;
  name: string;
  builder: string;
  category: string;
  useCases: string[];
  caps: string[];
  recommended?: boolean;
  installed?: boolean;
  /** Fallback initials if icon fails to load */
  mark: string;
  tint: string;
  /** Local Simple Icons SVG under /integrations/icons */
  icon: string;
};

export const integrationUseCases = [
  "All Integrations",
  "Lead Capture",
  "Ads & Attribution",
  "Messaging",
  "Scheduling",
  "Payments",
  "Website",
  "Automation",
] as const;

export const integrationCategories = [
  "Analytics",
  "Communication",
  "Advertising",
  "CRM & Sales",
  "Productivity",
  "Payments",
  "Hosting",
  "Social",
] as const;

function iconPath(id: string) {
  return `/integrations/icons/${id}.svg`;
}

export const integrationsFillers: IntegrationCard[] = [
  {
    id: "google-ads",
    name: "Google Ads",
    builder: "LeadsFlow Built",
    category: "Advertising",
    useCases: ["Ads & Attribution"],
    caps: ["Actions", "Sync", "Reports"],
    recommended: true,
    installed: true,
    mark: "G",
    tint: "#4285F4",
    icon: iconPath("google-ads"),
  },
  {
    id: "meta-ads",
    name: "Meta Ads",
    builder: "LeadsFlow Built",
    category: "Advertising",
    useCases: ["Ads & Attribution"],
    caps: ["Actions", "Audiences", "Reports"],
    recommended: true,
    installed: true,
    mark: "M",
    tint: "#0866FF",
    icon: iconPath("meta-ads"),
  },
  {
    id: "stripe",
    name: "Stripe",
    builder: "LeadsFlow Built",
    category: "Payments",
    useCases: ["Payments"],
    caps: ["Checkout", "Invoices", "Webhooks"],
    recommended: true,
    installed: true,
    mark: "S",
    tint: "#635BFF",
    icon: iconPath("stripe"),
  },
  {
    id: "gmail",
    name: "Gmail",
    builder: "LeadsFlow Built",
    category: "Communication",
    useCases: ["Messaging"],
    caps: ["Inbox", "Send", "Labels"],
    recommended: true,
    mark: "Gm",
    tint: "#EA4335",
    icon: iconPath("gmail"),
  },
  {
    id: "slack",
    name: "Slack",
    builder: "Community Built",
    category: "Communication",
    useCases: ["Messaging", "Automation"],
    caps: ["Alerts", "Actions"],
    mark: "Sl",
    tint: "#4A154B",
    icon: iconPath("slack"),
  },
  {
    id: "calendly",
    name: "Calendly",
    builder: "LeadsFlow Built",
    category: "Productivity",
    useCases: ["Scheduling"],
    caps: ["Bookings", "Sync"],
    installed: true,
    mark: "C",
    tint: "#006BFF",
    icon: iconPath("calendly"),
  },
  {
    id: "wordpress",
    name: "WordPress",
    builder: "LeadsFlow Built",
    category: "Hosting",
    useCases: ["Website", "Lead Capture"],
    caps: ["Forms", "Pages", "Sync"],
    recommended: true,
    mark: "W",
    tint: "#21759B",
    icon: iconPath("wordpress"),
  },
  {
    id: "zapier",
    name: "Zapier",
    builder: "Community Built",
    category: "Productivity",
    useCases: ["Automation"],
    caps: ["Triggers", "Actions"],
    mark: "Z",
    tint: "#FF4A00",
    icon: iconPath("zapier"),
  },
  {
    id: "hubspot",
    name: "HubSpot",
    builder: "Community Built",
    category: "CRM & Sales",
    useCases: ["Lead Capture"],
    caps: ["Contacts", "Deals"],
    mark: "H",
    tint: "#FF7A59",
    icon: iconPath("hubspot"),
  },
  {
    id: "mailchimp",
    name: "Mailchimp",
    builder: "Community Built",
    category: "Communication",
    useCases: ["Messaging"],
    caps: ["Lists", "Campaigns"],
    mark: "Mc",
    tint: "#FFE01B",
    icon: iconPath("mailchimp"),
  },
  {
    id: "linkedin",
    name: "LinkedIn Ads",
    builder: "LeadsFlow Built",
    category: "Advertising",
    useCases: ["Ads & Attribution"],
    caps: ["Campaigns", "Leads"],
    mark: "in",
    tint: "#0A66C2",
    icon: iconPath("linkedin"),
  },
  {
    id: "youtube",
    name: "YouTube Ads",
    builder: "LeadsFlow Built",
    category: "Advertising",
    useCases: ["Ads & Attribution"],
    caps: ["Video", "Reports"],
    mark: "Yt",
    tint: "#FF0000",
    icon: iconPath("youtube"),
  },
  {
    id: "twilio",
    name: "Twilio",
    builder: "LeadsFlow Built",
    category: "Communication",
    useCases: ["Messaging"],
    caps: ["SMS", "Voice"],
    installed: true,
    mark: "Tw",
    tint: "#F22F46",
    icon: iconPath("twilio"),
  },
  {
    id: "google-analytics",
    name: "Google Analytics",
    builder: "LeadsFlow Built",
    category: "Analytics",
    useCases: ["Ads & Attribution"],
    caps: ["Events", "Reports"],
    mark: "GA",
    tint: "#E37400",
    icon: iconPath("google-analytics"),
  },
  {
    id: "shopify",
    name: "Shopify",
    builder: "Community Built",
    category: "Payments",
    useCases: ["Payments", "Website"],
    caps: ["Orders", "Products"],
    mark: "Sh",
    tint: "#96BF48",
    icon: iconPath("shopify"),
  },
  {
    id: "instagram",
    name: "Instagram",
    builder: "LeadsFlow Built",
    category: "Social",
    useCases: ["Messaging", "Lead Capture"],
    caps: ["DM", "Publish"],
    mark: "Ig",
    tint: "#E4405F",
    icon: iconPath("instagram"),
  },
  {
    id: "facebook",
    name: "Facebook Pages",
    builder: "LeadsFlow Built",
    category: "Social",
    useCases: ["Messaging", "Lead Capture"],
    caps: ["Inbox", "Leads"],
    mark: "Fb",
    tint: "#1877F2",
    icon: iconPath("facebook"),
  },
  {
    id: "zoom",
    name: "Zoom",
    builder: "Community Built",
    category: "Productivity",
    useCases: ["Scheduling"],
    caps: ["Meetings", "Sync"],
    mark: "Zm",
    tint: "#2D8CFF",
    icon: iconPath("zoom"),
  },
  {
    id: "quickbooks",
    name: "QuickBooks",
    builder: "Community Built",
    category: "Payments",
    useCases: ["Payments"],
    caps: ["Invoices", "Sync"],
    mark: "Qb",
    tint: "#2CA01C",
    icon: iconPath("quickbooks"),
  },
  {
    id: "make",
    name: "Make",
    builder: "Community Built",
    category: "Productivity",
    useCases: ["Automation"],
    caps: ["Scenarios", "Webhooks"],
    mark: "Mk",
    tint: "#6D00CC",
    icon: iconPath("make"),
  },
];
